import { FormEvent, useState } from "react";
import { ArrowRight, ChevronLeft, ChevronRight, Circle, ExternalLink, Mail, MoveUpRight } from "lucide-react";
import { Link, useLocation } from "wouter";
import { toast } from "sonner";
import { trpc } from "@/lib/trpc";

const tracks = [
  { number: "01", title: "Product Design", meta: "10+ YEARS", copy: "Most aspects of design and business, end-to-end, while shipping a product." },
  { number: "02", title: "AI Workflows", meta: "AGENTS · DAILY", copy: "Practical AI workflows that turn repeated work into calm, dependable momentum." },
  { number: "03", title: "Design Systems", meta: "LIBRARY · 12 PARTS", copy: "Reusable systems that make every new surface clearer, faster, and easier to maintain." },
];
const work = [
  ["A1", "Hoopit AI", "Senior Product Designer", "AI-powered relationship intelligence for teams."],
  ["A2", "Santander UK", "Senior Product Designer", "Banking flows used by millions of customers."],
  ["A3", "Toyota", "Brand & Interface", "Product and brand interface work for a global automotive name."],
  ["A4", "Gjirafa", "UI / Product Designer", "Consumer products for the region’s largest tech company."],
  ["A5", "Nacew", "Product Designer", "AI-powered products for millions of users."],
];
const tools = ["Claude", "Figma", "Cursor", "Supabase", "Vercel", "OpenAI", "GitHub", "Tailwind"];

function Header() {
  const [location] = useLocation();
  const nav = [["Welcome", "/"], ["Work", "#work"], ["AI", "#ai"], ["Profile", "#profile"]];
  return <header className="site-header"><Link href="/" className="wordmark">vernika<span className="wordmark-dot">.</span></Link><nav>{nav.map(([label, href]) => <a className={location === href ? "active" : ""} key={label} href={href}>{label}{label === "Welcome" && <i />}</a>)}<span className="theme-dot" aria-label="Theme indicator"><Circle size={13} fill="currentColor" /></span><Link className="header-cta" href="/contact">Contact</Link></nav></header>;
}
function SectionTag({ children }: { children: string }) { return <div className="section-tag">{children}</div>; }
function ArrowButton({ direction = "right" }: { direction?: "left" | "right" }) { return <button className="square-button" aria-label={direction === "right" ? "Next" : "Previous"}>{direction === "right" ? <ChevronRight size={17} /> : <ChevronLeft size={17} />}</button>; }

function Workspace() {
  const [active, setActive] = useState(0);
  const items = ["Workspace", "AI Workflow", "Design System", "Product Design"];
  return <section className="workspace-wrap" aria-label="Vernika workspace preview"><div className="workspace-top"><span><b className="window-dot" /> <b className="window-dot" /> <b className="window-dot" /></span><span>PORTFOLIO / WORKSPACE / {items[active].toUpperCase()}</span><span className="status"><b /> READY</span></div><div className="workspace-body"><aside><small>EXPERTISE</small>{items.map((item, i) => <button key={item} className={active === i ? "selected" : ""} onClick={() => setActive(i)}><span className="mini-square" />{item}<em>{i === 0 ? "BENCH · LIVE" : i === 1 ? "AGENTS · DAILY" : i === 2 ? "LIBRARY · 12 PARTS" : "END TO END · 8+ YRS"}</em></button>)}<div className="opened">{active + 1} / 4 OPENED<div className="progress"><span style={{ width: `${(active + 1) * 25}%` }} /></div></div></aside><div className="workspace-canvas"><div className="canvas-head"><span>WORKSPACE</span><span>BENCH · LIVE</span></div><div className="flow"><span>BRIEF</span><i /> <span>EXPLORE</span><i /> <span>IN THE<br />SYSTEM?</span><i /> <span className="flow-active">REUSE</span><i /> <span className="ship">SHIP</span></div><div className="notes"><div className="note purple">Reuse before you add.<br />Every new pattern is<br />a thing somebody<br />has to maintain.</div><div className="note blue">Empty state?<br />ask design</div></div><div className="canvas-bottom"><span>FIGMA</span><span>CURSOR</span><span>CLAUDE</span><small>LIVE · NEVER FINISHED</small></div><div className="terminal"><p>· &nbsp; the portfolio — type `help`, or press a key below</p><p className="terminal-active">❯ &nbsp; open workspace</p><p>· &nbsp; opening the workspace</p><p>· &nbsp; ↳ Ask for it, draw it, ship it.</p><p className="terminal-ok">✓ &nbsp; workspace live — it carries on without you</p><div className="terminal-prompt">❯ &nbsp; try: open workspace <span><button>NEXT</button><button>HELP</button><button>CLEAR</button></span></div></div></div></div><div className="workspace-caption"><span>FIG. 004 — FOUR TRACKS, ONE BENCH</span><span>WORKSPACE, AI, SYSTEMS, PRODUCT — OPEN ONE ON THE LEFT</span></div></section>;
}
function Hero() { return <><section className="hero"><div className="hero-copy"><h1>I design apps, websites,<br />and <span>AI-powered systems</span></h1></div><div className="hero-aside"><p>10+ years designing the systems, brands and AI workflows behind products people actually use, serving millions of users every day.</p><div className="hero-actions"><a className="button primary" href="#work">View selected work <MoveUpRight size={15} /></a><a className="button secondary" href="#profile">About me <MoveUpRight size={15} /></a></div></div></section><div className="project-label"><span><b>04</b> <strong>Toyota</strong> <em>Brand & Interface</em></span><small>NEXT PROJECTS</small></div><Workspace /></> }
function Tracks() { const [selected, setSelected] = useState(0); const track = tracks[selected]; return <section id="profile" className="tracks"><SectionTag>TRACKS</SectionTag><div className="section-intro"><h2>Primarily <span>focused on</span></h2><p>Ten years of shipping, settled into three tracks that sharpen each other every day.</p></div><div className="track-content"><div className="isometric" aria-hidden="true"><div className="iso-base" /><div className="iso-block block-one" /><div className="iso-block block-two" /><div className="iso-block block-three" /><small>U1</small><small>1440 · 12 COL</small><small>ART</small></div><div className="track-copy"><h3>{track.title}</h3><small>{track.meta}</small><p>{track.copy}</p><div className="track-controls"><ArrowButton direction="left" /><button onClick={() => setSelected((selected + 1) % tracks.length)}><ArrowButton /></button></div></div></div><div className="track-tabs">{tracks.map((item, i) => <button key={item.title} onClick={() => setSelected(i)} className={selected === i ? "selected" : ""}>{item.number} / {item.title}</button>)}</div></section> }
function Numbers() { return <section className="numbers"><SectionTag>BY THE NUMBERS</SectionTag><div className="numbers-content"><h2>Ten years,<br /><span>by the numbers.</span></h2><p>Products shipped, teams joined, systems maintained — the decade<br />counted rather than described.</p><a href="#work">Read the full profile <ArrowRight size={15} /></a></div></section> }
function AI() { return <section id="ai" className="ai-section"><SectionTag>AI / DAILY PRACTICE</SectionTag><div><h2>AI is part of how I <span>design & build</span>, every day.</h2><p>Not a novelty — a daily practice. The tools that move a rough idea toward a shipped, working product.</p></div><div className="tool-list">{tools.map((tool, i) => <div key={tool}><span>{String(i + 1).padStart(2, "0")}</span>{tool}<ExternalLink size={13} /></div>)}</div></section> }
function Work() { return <section id="work" className="work-section"><SectionTag>WHERE I’VE WORKED</SectionTag><div className="work-grid">{work.map(([num, title, role, desc]) => <article key={title}><small>{num}</small><h3>{title}</h3><strong>{role}</strong><p>{desc}</p><ArrowRight size={15} /></article>)}</div><a className="text-link" href="#profile">Explore portfolio <ArrowRight size={15} /></a></section> }
function Footer() { return <footer><div><Link href="/" className="wordmark">vernika<span className="wordmark-dot">.</span></Link><p>Product design · Systems · AI</p></div><div className="footer-links"><a href="mailto:info@vernikatech.com"><Mail size={14} /> info@vernikatech.com</a><a href="#work">Work</a><a href="#ai">AI</a><Link href="/contact">Contact</Link></div><small>© 2026 Vernika. Built for better work.</small></footer> }
function Contact() { const [form, setForm] = useState({ name: "", email: "", company: "", message: "" }); const inquiry = trpc.inquiries.create.useMutation({ onSuccess: () => { toast.success("Inquiry sent — we’ll be in touch."); setForm({ name: "", email: "", company: "", message: "" }); }, onError: () => toast.error("Please check your details and try again.") }); const submit = (event: FormEvent) => { event.preventDefault(); inquiry.mutate(form); }; return <><Header /><main className="contact-page"><SectionTag>CONTACT</SectionTag><h1>Let’s make the next<br /><span>version tangible.</span></h1><p className="contact-lede">Tell us what’s getting in the way. We’ll bring a clear point of view and a practical next step.</p><form onSubmit={submit}><div className="form-row"><label>Name<input required value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} placeholder="Your name" /></label><label>Email<input required type="email" value={form.email} onChange={e => setForm({ ...form, email: e.target.value })} placeholder="you@company.com" /></label></div><label>Company<input value={form.company} onChange={e => setForm({ ...form, company: e.target.value })} placeholder="Your company" /></label><label>What are you working through?<textarea required minLength={10} rows={5} value={form.message} onChange={e => setForm({ ...form, message: e.target.value })} placeholder="Tell us a little about the project" /></label><button className="button primary" disabled={inquiry.isPending}>{inquiry.isPending ? "Sending…" : "Send inquiry"} <ArrowRight size={15} /></button></form></main><Footer /></> }
function HomePage() { return <><Header /><main><Hero /><Tracks /><Numbers /><AI /><Work /><section className="closing"><h2>Good systems create<br /><span>room for good decisions.</span></h2><Link className="button primary" href="/contact">Start a conversation <ArrowRight size={15} /></Link></section></main><Footer /></> }
export default function Home() { const [location] = useLocation(); return location === "/contact" ? <Contact /> : <HomePage />; }
